apiVersion: v1
kind: Pod
metadata:
  name: roche-dev-broken-fixed
  namespace: roche-dev
spec:
  securityContext:
    fsGroup: 2000
    runAsUser: 1000
    runAsGroup: 3000
    runAsNonRoot: true
  containers:
    - name: nginx
      image: nginxinc/nginx-unprivileged
      ports:
        - containerPort: 8080
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
